name: Base Checks

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      uses: bahmutov/npm-install@v1
      with:
       useLockFile: false
    - name: еуяе build
      run: |
        vue-cli-service build
      env:
        CI: true
